### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mottosso** [tokejepsen/filelink#4]
Let's get AppVeyor and Travis into the game, with tests for Windows and Unix.

**Comment by tokejepsen** [comment]
Yeah, that sounds like a good idea :)

When do you think is a good time to start testing? Since the module is still under development, lots could change, even something like the arguments to the methods.

**Comment by mottosso** [comment]
I think now is a good time. If only to document and assert for ourselves things like #3 and flesh out all other edge cases and obscurities that we find as we develop. Ideally we'd submit PRs with just tests, and work out the implementation from there.

**Comment by tokejepsen** [comment]
How come we need both AppVeyor and Travis for tests?

**Comment by mottosso** [comment]
AppVeyor does Windows, Travis does Unix

**Comment by tokejepsen** [comment]
Ahh :)

What about the testing framework? You have more experience with them than I, but seems like nose2 might be a good choice?

**Comment by mottosso** [comment]
Up to you :) I tend to go with nose, but it's a personal choice. I've heard good things about py.test too.

**Comment by tokejepsen** [comment]
The testing framework ended up being pytest :)
